# TODO: Do some of these..!
#    # Check templates and such for style= attributes
#    - if [[ `grep -rnw src/templates/ -e 'style='` ]]; then (exit -1); fi
#    - if [[ `grep -rnw src/static/riot -e 'style='` ]]; then (exit -1); fi
#    # - if [[ `grep -rnw src -e 'TODO'` ]]; then (exit -1); fi

version: 2

jobs:
  test:
    environment:
      BASH_ENV: ~/.nvm/nvm.sh
    docker:
      - image: circleci/python:3.6-jessie-browsers

    pre:
      # Make our environment take all .env variables MAKE SURE THIS MATCHES $BASH_ENV!
      - run: echo "set -o allexport; source .env_sample; set +o allexport" >> ~/.nvm/nvm.sh

    steps:
      - checkout
      - setup_remote_docker

      # Directory for any test reports
      - run: mkdir test-reports

      # Setup env, background tasks, cache
      - run: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
      - run: nvm install 6.14.4
      - run: npm install stylus riot -g
      - run: npm run build-stylus
      - run: npm run build-riot
      - run: cp .env_sample .env
      - run: docker-compose run -d minio
      - run: docker-compose run createbuckets
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log -enablePassThrough false
          background: true
      - run: sudo pip install -r requirements.dev.txt
      - save_cache:
          key: codalab-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements.dev.txt" }}
          paths:
            - ~/.cache/pip
      - run: python manage.py collectstatic --noinput

      # Tests
      - run: mkdir artifacts/
      - run: py.test -m "not e2e"
      - run: py.test -m e2e
      - store_artifacts:  # like screenshots
          path: artifacts/
      - run: flake8 src/ --ignore E501

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
