# TODO: Do some of these..!
#    # Check templates and such for style= attributes
#    - if [[ `grep -rnw src/templates/ -e 'style='` ]]; then (exit -1); fi
#    - if [[ `grep -rnw src/static/riot -e 'style='` ]]; then (exit -1); fi
#    # - if [[ `grep -rnw src -e 'TODO'` ]]; then (exit -1); fi

version: 2

jobs:
  test:
    pre: ./manage.py collectstatic
    docker:
      - image: circleci/python:3.6-jessie-browsers
    steps:
      - checkout

      # Directory for any test reports
      - run: mkdir test-reports

      # Setup env, background tasks, cache
      - run: npm install npm-watch stylus riot -g
      - run: npm run build-stylus
      - run: npm run build-riot
      - run: python manage.py collectstatic --noinput
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log -enablePassThrough false
          background: true
      - run: sudo pip install -r requirements.dev.txt
      - save_cache:
          key: codalab-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements.dev.txt" }}
          paths:
            - ~/.cache/pip

      # Tests
      - run: mkdir artifacts/
      - run: py.test -m "not e2e"
      - run: py.test -m e2e
      - store_artifacts:  # like screenshots
          path: artifacts/
      - run: flake8 src/ --ignore E501

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
